namespace RGamaFelix.CqrsDispatcher.Query.Pipeline.Request;

/// <summary>
///   Provides a base implementation for an extension that handles query requests within the CQRS dispatcher pipeline.
/// </summary>
/// <typeparam name="TRequest">The type of the query request that this extension processes.</typeparam>
/// <typeparam name="TResponse">The type of the response generated by the query request.</typeparam>
public abstract class QueryRequestExtensionBase<TRequest, TResponse> : IQueryRequestExtension<TRequest, TResponse>
  where TRequest : IQueryRequest<TResponse>
{
  /// <inheritdoc />
  public virtual int? Order { get; } = 0;

  /// <inheritdoc />
  public abstract Task<TResponse> Handle(TRequest request, Func<TRequest, CancellationToken, Task<TResponse>> next,
    CancellationToken cancellationToken);

  /// <inheritdoc />
  public virtual bool ShouldRun(TRequest request)
  {
    return true;
  }
}